apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: userservice
    context: src/userservice
    custom:
      buildCommand: |
        docker buildx build --platform linux/amd64,linux/arm64 -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/userservice:$(git rev-parse --short HEAD) -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/userservice:latest .
      pushCommand: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/userservice:$(git rev-parse --short HEAD)
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/userservice:latest
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true