apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: userservice
    context: src/userservice
    custom:
      buildCommand: |
        docker buildx build --platform linux/amd64,linux/arm64 -t \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ecomm/userservice:$(git rev-parse --short HEAD) \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ecomm/userservice:latest --output type=image,push=true .
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
  